### ISSUE TITLE
Example depends on removed `Context`

### ISSUE THREAD

**Issue by BourgondAries** [kkawakam/rustyline#197]
At least since 3.0.0, Context appears to be removed. The example in this repo depends on this.

**Comment by gwenn** [comment]
Could you please tell me where there is a problem exactly ?
All seems fine in `master` branch.
Idem in `v3.0.0` tag.

**Comment by BourgondAries** [comment]
Might be a publishing issue since building the repo and example is fine, but it's not if you create a new binary using it. 
Reproducing:
```
cargo new whatever
cd whatever
echo 'rustyline = "3.0.0"' >> Cargo.tom
cp ../rustyline/examples/example.rs src/main.rs
cargo run
```

**Comment by gwenn** [comment]
All is fine on my side:
```sh
cargo new whatever
cd whatever/
echo 'rustyline = "3.0.0"' >> Cargo.toml
echo 'log = "0.4"' >> Cargo.toml
cp ../rustyline-v3/examples/example.rs src/main.rs # only v3 will work
cargo run
```

**Comment by BourgondAries** [comment]
What version are you running, I'm on `cargo 1.33.0-nightly (2cf1f5dda 2018-12-11)`
Also if you go on docs:
https://docs.rs/rustyline/3.0.0/rustyline/?search=Context

There's nothing

**Comment by gwenn** [comment]
And there is no `Context` either in associated [example](https://docs.rs/crate/rustyline/3.0.0/source/examples/example.rs) so all is fine.

**Comment by BourgondAries** [comment]
There is in this repo :O

**Comment by gwenn** [comment]
Indeed, breaking change was introduced by https://github.com/kkawakam/rustyline/pull/179.
For me, rustyline version 1.0 is a "premature stabilisation"...

**Comment by gwenn** [comment]
`History` cannot be disabled, you can only set its [max length](https://docs.rs/rustyline/3.0.0/rustyline/history/struct.History.html#method.set_max_len) to zero.
And I am not sure but for me you cannot keep a reference to `History` while reading.

**Comment by gwenn** [comment]
Proof:
```rust
error[E0502]: cannot borrow `rl` as mutable because it is also borrowed as immutable
   --> examples/example.rs:82:24
    |
81  |         let history = rl.history();
    |                       -- immutable borrow occurs here
82  |         let readline = rl.readline(PROMPT);
    |                        ^^^^^^^^^^^^^^^^^^^ mutable borrow occurs here
...
101 |         println!("history: {:?}", history.len())
    |                                   ------- immutable borrow used here, in later iteration of loop
```

**Comment by gwenn** [comment]
In [liner](https://github.com/MovingtoMars/liner/blob/ba7f4444c3514522a399371f7af9b86006e79bdb/src/editor.rs#L584), suggestions/hints are not customisable.

**Comment by BourgondAries** [comment]
Been reading https://github.com/kkawakam/rustyline/pull/179/files a bit more closely (sorry, I'm quite tired atm) and I think I understand it now. I was under the impression context held _autocompletion_ history (which can indeed be refcelled), but your commit appears to expose an immutable ref to the actual command history.

That seems OK actually, but hopefully that's the end of adding to the traits. Is your idea to - in the future, perhaps - add more things to Context? At least that'd keep user impls backwards compatible.

**Comment by gwenn** [comment]
Thanks for your feedback.
I am afraid that there is still an important piece missing: an incremental tokenizer/parser.
Currently, `Completer`/`Hinter`/`Highlighter`/[`Validator`](https://github.com/kkawakam/rustyline/pull/182#issuecomment-454908390) implementations must do their own parsing.
We need to introduce another `Tokenizer` trait which provides a `TokenTree`.
And this `TokenTree` can then be used by our helpers.

```rust
pub trait Tokenizer {
  type TokenTree;

  fn create_token_tree(&self); // TODO Validate: if we can keep a mutable reference to Tokenizer => useless
  fn parse(&self, tt: &mut Self::TokenTree, delta: InputEdit);
  // or
  fn parse(&mut self, delta: InputEdit);
  fn token_tree(&self) -> Self::TokenTree;
}
```
When you have access to a `TokenTree`, highlighting/hinting are easy to implement.

**Comment by gwenn** [comment]
https://github.com/kkawakam/rustyline/commit/806ddccbb18b2e2bd490bbbe6d72c3a1833e2c1b#diff-b4aea3e418ccdb71239b96952d9cddb6R624
```
/// TODO Tokenizer/parser used for both completion, suggestion, highlighting.
/// (parse current line once)
```
Six months ago...

**Comment by BourgondAries** [comment]
Sounds useful, but why not just make this part of a `Highlighter`? Let it do the parsing. Such a tokenizer makes me think that the project will overextend itself by doing too much.

It's already quite jading as a user to have to impl `Completer` and especially `Highlighter` when I just want a simple `Hinter`, and do not care about the other two. My hinter also needs no parsing (or Tokenizer), just checks if the last `char == ' '`.

I'd love to see this crate become stable so that we can all build stuff on top of it instead of it ever-expanding and eventually inventing its own config language which then evolves into a turing-complete language to perform readline functionality.

**Comment by gwenn** [comment]
You can still have a `Tokenizer` that does nothing (`type TokenTree = ();`).
But you want to parse once (incrementally) and then complete/suggest/highlight/validate.
You cannot do this inside the `Completer` because it is used only when TAB is pressed.

`rustyline` version 1.0 was a `linenoise` clone.
`rustyline` version ??? will attempt to be a `prompt_toolkit` clone (currently prompt_toolkit `lexer` seems to be used only for highlighting).

`jline3` uses a [parser](https://github.com/jline/jline3/blob/a24636dc5de83baa6b65049e8215fb372433b3b1/reader/src/main/java/org/jline/reader/Parser.java) for [completion](https://github.com/jline/jline3/blob/a24636dc5de83baa6b65049e8215fb372433b3b1/reader/src/main/java/org/jline/reader/Completer.java).

**Comment by gwenn** [comment]
And I know: if you want only completion, you need this boilerplate:
https://github.com/kkawakam/rustyline/blob/master/src/test/mod.rs#L41
```
impl Helper for SimpleCompleter {}
impl Hinter for SimpleCompleter {}
impl Highlighter for SimpleCompleter {}
```
And I have no solution...

**Comment by BourgondAries** [comment]
>But you want to parse once (incrementally) and then complete/suggest/highlight/validate.

Can't this be done incrementally in the hinter?

**Comment by gwenn** [comment]
hinter has no access to the delta/edit action.
And the hinter is called just before rendering, not before completion.

**Comment by BourgondAries** [comment]
Can't you deduce the delta/edit inside the hinter though? You store current and on the next invocation you can compute the diff.

**Comment by BourgondAries** [comment]
Alright, well, this issue is resolved I guess. So I'll close it
